import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class about_app extends StatelessWidget {
  const about_app({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        appBar: AppBar(
          leading: IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
        ),
        body: ListView(children: [
          AboutApp(),
        ]),
      ),
    );
  }
}

class AboutApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final screenHeight = MediaQuery.of(context).size.height;

    return Column(
      children: [
        Container(
          width: screenWidth,
          height: screenHeight,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF454F82)),
          child: Stack(
            children: [
              Positioned(
                left: screenWidth * 0.05,
                top: screenHeight * 0.16,
                child: Container(
                  width: screenWidth * 0.9,
                  height: screenHeight * 0.7,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF9586A8)),
                      borderRadius: BorderRadius.circular(27),
                    ),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text(
                      'Sistem aplikasi ini dapat membantu dan mempermudah masyarakat awam yang kurang mengerti tentang bahasa isyarat seputar warna. \n\nSistem ini dapat diimplementasikan pada sebuah toko seperti toko baju ataupun lainnya ketika ada penyandang disabilitas yang ingin memilih barang sesuai dengan warna yang diinginkan.',
                      style: TextStyle(
                        color: Color(0xFF3C5688),
                        fontSize: screenHeight * 0.03,
                        fontFamily: 'ABeeZee',
                        fontWeight: FontWeight.w400,
                        height: 1.5, // Increased height for better readability
                        letterSpacing: -0.41,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: screenWidth * 0.12,
                top: screenHeight * 0.04,
                child: SizedBox(
                  width: screenWidth * 0.76,
                  height: screenHeight * 0.1,
                  child: Text(
                    'About App',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: screenHeight * 0.04,
                      fontFamily: 'Abril Fatface',
                      fontWeight: FontWeight.w400,
                      height: 1,
                      letterSpacing: -0.41,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
